# Default path
app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

# User path
user_index:
    path:     /user/books
    defaults: { _controller: AppBundle:User:index }

user_borrow:
    path:     /library/book/{slug}/borrow
    defaults: { _controller: AppBundle:User:borrow }

user_return_book:
    path:     /library/book/{slug}/return
    defaults: { _controller: AppBundle:User:returnBook }

# Admin path
admin_index:
    path:     /admin
    defaults: { _controller: AppBundle:Admin:index }

admin_users_list:
    path:     /users
    defaults: { _controller: AppBundle:Admin:users }
