app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

user_borrow:
    path:     /library/book/{slug}/borrow
    defaults: { _controller: AppBundle:User:borrow }

user_return_book:
    path:     /library/book/{slug}/return
    defaults: { _controller: AppBundle:User:returnBook }

user_index:
    path:     /user/books
    defaults: { _controller: AppBundle:User:index }
