library_homepage:
    path:     /
    defaults: { _controller: EBookLibraryBundle:Default:index }

library_books:
    path:     /book
    defaults: {_controller: EBookLibraryBundle:Default:viewBooks}

library_book:
    path:     /book/{slug}
    defaults: {_controller: EBookLibraryBundle:Default:viewBook}
    requirements:
        page: \d+

library_add:
    path:     /add
    defaults: { _controller: EBookLibraryBundle:Default:addBook }
