library_homepage:
    path:     /{page}
    defaults: 
        _controller: EBookLibraryBundle:Default:index
        page:        1
    requirements:
        page: \d+

library_book:
    path:     /book/{slug}
    defaults: {_controller: EBookLibraryBundle:Default:viewBook}
    requirements:
        page: \d+

library_add:
    path:     /add
    defaults: { _controller: EBookLibraryBundle:Default:addBook }
