# Default path
library_homepage:
    path:     /{page}
    defaults: 
        _controller: EBookLibraryBundle:Default:index
        page:        1
    requirements:
        page: \d+

library_book:
    path:     /book/{slug}
    defaults: {_controller: EBookLibraryBundle:Default:viewBook}

library_read_book:
    path:     /book/{slug}/reader
    defaults: {_controller: EBookLibraryBundle:Default:bookReader}

# Management path
library_add_book:
    path:     /add/book
    defaults: { _controller: EBookLibraryBundle:Management:addBook }

library_edit_book:
    path:     /book/{slug}/edit
    defaults: { _controller: EBookLibraryBundle:Management:editBook }

library_delete_book:
    path:     /book/{slug}/delete
    defaults: { _controller: EBookLibraryBundle:Management:deleteBook }
