ktbs:
    resource: "@KtbsBundle/Resources/config/routing.yml"
    prefix:   /

e_book_library:
    resource: "@EBookLibraryBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
