user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

ktbs:
    resource: "@KtbsBundle/Resources/config/routing.yml"
    prefix:   /

e_book_library:
    resource: "@EBookLibraryBundle/Resources/config/routing.yml"
    prefix:   /library

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    pattern:   /login
    defaults:  { _controller: UserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout
