<?php

namespace LeHibouc\EBookLibraryBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{
	public function getBooks($page, $nbPerPage)
	{
		$query = $this->createQueryBuilder('b')
		  ->orderBy('b.title', 'DESC')
		  ->getQuery()
		;

		$query
		  ->setFirstResult(($page-1) * $nbPerPage)
		  ->setMaxResults($nbPerPage)
		;
		
		return new Paginator($query, true);
	}
}
