<?php

namespace LeHibouc\EBookLibraryBundle\Repository;

/**
 * EpubFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpubFileRepository extends \Doctrine\ORM\EntityRepository
{
}
